apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: apollodb
  namespace: default
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 80
      containers:
        - image: gcr.io/PROJECT_ID/apollodb:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
